apps/base/urls.py
from django.conf.urls import url

from .views import LandingView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'),
]

apps/groups/urls.py
from django.conf.urls import url

from .views import (
    BlockView, CommentView, CreateView, EditView, GroupView, InviteView,
    JoinView, LeaveView, UnblockView
)

app_name = 'group'
urlpatterns = [
    url(r'^(?P<pk>\d+)/$', GroupView.as_view(), name='page'),
    url(r'^(?P<pk>\d+)/block/$', BlockView.as_view(), name='block'),
    url(r'^(?P<pk>\d+)/unblock/$', UnblockView.as_view(), name='unblock'),
    url(r'^(?P<pk>\d+)/join/$', JoinView.as_view(), name='join'),
    url(r'^(?P<pk>\d+)/leave/$', LeaveView.as_view(), name='leave'),
    url(r'^(?P<pk>\d+)/comment/$', CommentView.as_view(), name='comment'),
    url(r'^(?P<pk>\d+)/invite/$', InviteView.as_view(), name='invite'),
    url(r'^(?P<pk>\d+)/edit/$', EditView.as_view(), name='edit'),
    url(r'^create/$', CreateView.as_view(), name='create'),
]

pollyandbob/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('apps.base.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('allauth.urls')),
    url(r'^groups/', include('apps.groups.urls')),
    url(r'^listings/', include('apps.listings.urls')),
    url(r'^comments/', include('fluent_comments.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^notifications/', include('apps.notifications.urls')),
    url(r'^', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
from django.contrib.gis.db import models
from django.utils.translation import ugettext_lazy as _


class BaseImage(models.Model):
    """
    Honestly I didn't get where do we use it
    # ASK: does anybody know why do we need this model?
    """
    image = models.ImageField(_("image file"), upload_to='images')
    created_at = models.DateTimeField(
        _("created at"), auto_now_add=True, editable=False)
    content = models.TextField(_("image description"))

    class Meta:
        ordering = ['created_at']
        verbose_name = _("image")
        verbose_name_plural = _("images")


# class Language(models.Model):
#     code =

apps/groups/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from sorl.thumbnail import get_thumbnail

from apps.utils.models import ThumbnailMixin


class Group(models.Model, ThumbnailMixin):
    STATUS_OPEN = 1
    STATUS_CLOSED = 2
    STATUS_SECRET = 3
    STATUS_CHOICES = (
        (STATUS_OPEN, _('Open')),
        (STATUS_CLOSED, _('Closed')),
        (STATUS_SECRET, _('Secret')),
    )

    title = models.CharField(_('Group name'), max_length=120)
    created_at = models.DateTimeField(_('Created at'),
                                      auto_now_add=True, null=True)
    status = models.IntegerField(
        _('Group status'), choices=STATUS_CHOICES, db_index=True,
        default=STATUS_OPEN, null=True)
    image = models.ImageField(_('Image file'), upload_to='images')
    content = models.TextField(_('Group description'))
    position = models.PointField(_('Geo location'), null=True)

    admins = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='administrated_groups',
        verbose_name=_('Group administrators'), blank=True)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='groups',
        verbose_name=_('Group members'), blank=True)
    blocked_by_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='blocked_groups', editable=False)

    class Meta:
        verbose_name = _("Group")
        verbose_name_plural = _("Groups")

    def __str__(self):
        return 'Group: %s' % self.name

    def get_absolute_url(self):
        return reverse('group:page', args=(self.id,))

    def to_list_display(self):
        category = {'url': '', 'value': 'Groups'}
        return {
            'category': category,
            'image': self.thumbnail_image,
            'title': self.name,
            'text': self.description,
            'creator':None,
            'url': reverse('pb_group', kwargs={'group_id':self.pk}),
            'position': self.position,
            'distance': self.distance.m,
        }

    @property
    def large_image(self):
        return get_thumbnail(self.image, '1280x400', crop='top').url


class GroupThread(models.Model):
    group = models.ForeignKey(
        Group, related_name='threads', verbose_name=_('Group'))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Created at'))

    def __str__(self):
        return "Thread for group: %s" % self.group.name

apps/groups/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Group, GroupThread

#
# class CommentForm(forms.ModelForm):
#     """
#     Form to create group comment
#     """
#     thread = forms.IntegerField(required=False)
#
#     class Meta:
#         model = ThreadComment
#         fields = ['text', 'thread']
#
#     def __init__(self, *args, **kwargs):
#         self._author = kwargs.pop('author')
#         self._group = kwargs.pop('group')
#         super(CommentForm, self).__init__(*args, **kwargs)
#
#     def save(self, commit=True, *args, **kwargs):
#         instance = super().save(commit=False)
#         instance.author = self._author
#
#         if self.cleaned_data['thread']:
#             thread = GroupThread.objects.get(id=self.cleaned_data['thread'])
#         else:
#             thread = GroupThread(group=self._group)
#             thread.save()
#
#         instance.thread = thread
#
#         if commit:
#             instance.save()
#
#         return instance
#
#     def clean(self):
#         """
#         if group is closed and not in group raise error
#         """
#         is_in_group = self._author.is_in_group(self._group)
#         if not is_in_group and self._group.status == self.group.STATUS_CLOSED:
#             raise forms.ValidationError(_("You cannot comment in this group!"))


class UsersForm(forms.Form):
    """
    Form to get users to invite
    """
    users = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super(UsersForm, self).__init__(*args, **kwargs)
        self.fields['users'].choices = [(neighbour.id, neighbour.id) for
                                        neighbour in self._user.neighbours()]

    def clean_users(self):
        return [int(user) for user in self.cleaned_data['users']]


class GroupForm(forms.ModelForm):
    """
    Form to create/update group
    """

    class Meta:
        model = Group
        fields = ['status', 'content', 'title']

apps/base/views.py
from django.forms import formset_factory
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from apps.users.forms import EmailForm
from apps.users.tasks import send_email


class LandingView(TemplateView):
    template_name = 'base/landing.html'

    def get_invite_friends_formset(self):
        formset = formset_factory(EmailForm, extra=3)
        return formset(data=self.request.POST or None, prefix='invite_friends')

    def get_context_data(self, **kwargs):
        kwargs.update({
            'invite_friends_formset': self.get_invite_friends_formset()
        })
        return super(LandingView, self).get_context_data(**kwargs)

    def invite_friend(self, form):
        if 'email' in form.cleaned_data:
            send_email.apply_async(kwargs={
                'subject': _('Invitation to Polly & Bob'),
                'message_template': 'users/emails/invite_to_site.html',
                'to': form.cleaned_data['email']
            })

    def post(self, request, *args, **kwargs):
        formset = self.get_invite_friends_formset()
        if formset.is_valid():
            [self.invite_friend(form) for form in formset]
        return HttpResponseRedirect(reverse('landing'))

apps/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View
from django.views.generic.detail import DetailView, SingleObjectMixin

from .models import Group
from .forms import UsersForm
from .tasks import invite_neighbour


class GroupView(DetailView):
    model = Group

    @property
    def is_user_in_group(self):
        if not self.request.user.is_anonymous():
            return self.request.user.is_in_group(self.object)
        return False

    @property
    def is_group_admin(self):
        if not self.request.user.is_anonymous():
            return self.request.user.is_group_admin(self.object)
        return False

    @property
    def is_blocked(self):
        if not self.request.user.is_anonymous() \
                and self.request.user.is_group_blocked(self.object):
            return True
        return False

    def get_context_data(self, **kwargs):
        group = self.get_object()
        members = list(group.members.values_list('id', flat=True))
        admins = list(group.admins.values_list('id', flat=True))
        pks = members + admins
        neighbours = self.request.user.neighbours().exclude(id__in=pks)

        kwargs.update({
            'is_in_group': self.is_user_in_group,
            'is_in_group_admins': self.is_group_admin,
            'is_blocked': self.is_blocked,
            'neighbours': neighbours
        })
        return super(GroupView, self).get_context_data(**kwargs)


class BlockView(LoginRequiredMixin, View):
    """
    View to join group
    """
    def get(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs.get('pk'))
        request.user.blocked_groups.add(group)
        return HttpResponseRedirect(group.get_absolute_url())


class UnblockView(LoginRequiredMixin, View):
    """
    View to join group
    """
    def get(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs.get('pk'))
        request.user.blocked_groups.remove(group)
        return HttpResponseRedirect(group.get_absolute_url())


class JoinView(LoginRequiredMixin, View):
    """
    View to join group
    """
    def get(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs.get('pk'))
        group.members.add(request.user)
        return HttpResponseRedirect(group.get_absolute_url())


class LeaveView(View):
    """
    View to leave group
    """
    def get(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs.get('pk'))
        group.members.remove(request.user)
        group.admins.remove(request.user)
        return HttpResponseRedirect(group.get_absolute_url())


class CommentView(LoginRequiredMixin, SingleObjectMixin, View):
    """
    View to leave group
    """
    model = Group

    def get_form(self):
        return CommentForm(
            data=self.request.POST, user=self.request.user,
            group=self.get_object())

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(self.get_object().get_absolute_url())


class InviteView(LoginRequiredMixin, View):
    """
    View to leave group
    """
    def post(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs.get('pk'))

        form = UsersForm(data=request.POST, user=request.user)
        if form.is_valid():
            neighbours = form.cleaned_data['users']
            for neighbour_id in neighbours:
                invite_neighbour.apply_async(kwargs={
                    'user_id': request.user.id,
                    'neighbour_id': neighbour_id,
                    'group_id': group.id
                })
        return HttpResponseRedirect(group.get_absolute_url())


class EditView(TemplateView):
    """
    View to leave group
    """
    template_name = 'groups/create.html'

    def get(self, request, *args, **kwargs):
        pass


class CreateView(TemplateView):
    """
    View to leave group
    """
    template_name = 'groups/create.html'

    def get_form(self):
        return GroupForm(data=request.POST or None)

    def get_context_data(self, **kwargs):
        kwargs.update({
            'form': self.get_form()
        })
        return super(CreateView, self).get_context_data(**kwargs)

apps/groups/templates/groups/base.html
{% extends "base/base.html" %}

{% load i18n %}

{% block banner %}
<!--banner part start-->
<section class="banner_outer listing groups_info">
{% if is_blocked %}
  <a href="{% url 'group:unblock' object.pk %}" class="block_btn">{% trans "Unblock" %}</a>
{% else %}
  <a href="{% url 'group:block' object.pk %}" class="block_btn">{% trans "Block" %}</a>
{% endif %}
  <div class="container">
    <div class="row">
      <div class="banner_inr">
        <div class="open_left"><h3>{{ object.name }}</h3></div>
        <div class="open_right open_rig">
          <div class="open_left_bottom">
             {% ifequal object.status object.STATUS_OPEN %}
                  <div class="secret open_secr">{{ object.get_status_display }} {% trans "group" %}</div>
             {% endifequal %}
             {% ifequal object.status object.STATUS_CLOSED %}
                  <div class="secret closed">{{ object.get_status_display }} {% trans "group" %}</div>
             {% endifequal %}
             {% ifequal object.status object.STATUS_SECRET %}
                  <div class="secret secr">{{ object.get_status_display }} {% trans "group" %}</div>
             {% endifequal %}
         </div>
          <div class="jx">
          {% if request.user.is_authenticated %}
            {% if is_in_group %}
              <a href="{% url 'group:leave' object.id %}" class="block_btn_cnt_j">{% trans "Leave" %}</a>
            {% else %}
              <a href="{% url 'group:join' object.id %}" class="block_btn_cnt_j">{% trans "Join" %}</a>
            {% endif %}
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% if is_in_group_admins %}
  <a class="edit_btn_admin" href="#">{% trans "Edit" %}</a>
  {% endif %}
</section>
<!--banner part end-->
{% endblock %}

{% block javascript %}
<!--accordination-->
<script type="text/javascript">
	$(function() {

	    var menu_ul = $('.hide_part'),
	           menu_a  = $('.open');

	    menu_ul.hide();

	    menu_a.click(function(e) {
	        e.preventDefault();
	        if(!$(this).hasClass('active')) {
	            menu_a.removeClass('active');
	            menu_ul.filter(':visible').slideUp('normal');
	            $(this).addClass('active').next().stop(true,true).slideDown('normal');
	        } else {
	            $(this).removeClass('active');
	            $(this).next().stop(true,true).slideUp('normal');
	        }
	    });

	});
</script>
<!--accordination-->
{% endblock %}

apps/groups/templates/groups/group_create.html
{% extends "groups/base.html" %}

{% load i18n staticfiles %}

{% block title %}
    {% trans "Create group" %} - {{ block.super }}
{% endblock %}

{% block banner %}{% endblock %}

{% block content %}
<!--content part start-->
<section class="content_outer content_outer_nm crg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 content_inner">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 content_left">
          <div class="content_helper content_helper_2">
            <div class="helper_main">
              <div class="clear_top">
                <h3 class="title_left">{% trans "Choose option" %}</h3>
              </div>
              <ul class="content_list" id="top">
                <li><a href="#">{% trans "Events" %} (25)</a></li>
                <li><a href="#">{% trans "Neighbors" %} (455)</a></li>
                <li><a href="#">{% trans "help needed" %} (12)</a></li>
                <li><a href="#">{% trans "services needed" %} (39)</a></li>
                <li><a href="#">{% trans "Services Offered" %} (120)</a></li>
                <li><a href="#">{% trans "Goods Needed" %} (21)</a></li>
                <li><a href="#">{% trans "Goods Offered" %} (1,421)</a></li>
                <li><a href="#">{% trans "Neighborhood News" %} (12)</a></li>
                <li><a href="#">{% trans "People Needed" %} (12)</a></li>
                <li><a href="#">{% trans "Groups" %} (32)</a></li>
              </ul>
              <div class="category_inr">
                <div class="drp">
                      <!--<select>
                          <option>select your options</option>
                      </select>-->
                  <div class="dropdown mega-dropdown">
                    <a href="javascript:;" class="dropdown-toggle" id="menu4">{% trans "select your options" %}</a>
                    <div class="dropdown-menu mega-dropdown-menu">
                      <ul>
                        <li><label><input name="" type="checkbox" value="" id="checkAll"><strong>
                          {% trans "Mark all" %}</strong></label></li><li><label>
                          <input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Events" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Neighbors" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "People Needed" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Groups" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Services Needed" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Services Offered" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Help Needed" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Help Offered" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Goods Needed" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Goods Offered" %}</label></li>
                        <li><label><input name="" type="checkbox" value="" class="checkItem">
                          {% trans "Neighborhood News" %}</label></li>
                      </ul>
                      <a href="#" class="save_btn">{% trans "Save" %}</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12  content_right title_right">
          <div class="title_right_top">
            <div class="fr">
              <h3>{% trans "Title" %}</h3>
              <input name="" type="text" class="add_text" placeholder="{% trans "Add Title" %}">
            </div>
          </div>
          <div class="title_right_bottom">
            <div class="image_upload">
              <img src="{% static "images/placeholder_img.png" %}" alt="">
              <a href="#" class="no_btn upload_btn" > {% trans "Upload Picture" %}</a>
            </div>
          </div>
        </div>
        <div class="about_me_outer des">
          <div class="add_des">
            <h3>{% trans "Description" %}</h3>
              <textarea name="" cols="" rows="" class="add_des_field" placeholder="{% trans "Add Description" %}"></textarea>
          </div>
        </div>
        <div class="about_me_outer des">
          <div class="add_des">
            <h3>{% trans "Choose type of group:" %}</h3>
            <a href="#" class="open_btn mt">{% trans "open" %}</a>
            <a href="#" class="open_btn closed_btn mt">{% trans "closed" %}</a>
            <a href="#" class="open_btn mt">{% trans "secret" %}</a>
          </div>
        </div>
        <div class="invite_bottom">
          <div class="invite listing_left">
            <div class="dropdown mega-dropdown4">
              <a href="javascript:;"  id="menu4" class="direct dropdown-toggle invite_btn"><!--Invite some neighbors directly!--> {% trans "Invite Some Neighbors" %}  <i class="fa fa-caret-down"></i></a>
              <div class="dropdown-menu mega-dropdown-menu4 setting user_block direct_block">
                <div class="user_block_outer">
                  <div class="user_block_top gray">
                    <div class="user_block_top_left"><img src="images/banner_image2.jpg" alt=""></div>
                    <div class="user_block_top_right">Peter <input name="" type="checkbox" value=""></div>
                  </div>
                  <div class="user_block_top">
                    <div class="user_block_top_left"><img src="images/banner_image2.jpg" alt=""></div>
                    <div class="user_block_top_right">Peter <input name="" type="checkbox" value=""></div>
                  </div>
                </div>
                <div class="user_bottom user_bottom_3"><!--20 neighbors.-->{% trans "Choose maximum 100 neighbors." %} </div>
              </div>
            </div>
          </div>
          <a href="#" class="open_btn closed_btn publish_btn">{% trans "publish" %}</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--content part end-->
{% endblock %}

apps/groups/templates/groups/group_detail.html
{% extends "groups/base.html" %}

{% load staticfiles i18n humanize comments %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'fluent_comments/css/ajaxcomments.css' %}" />
{% endblock %}

{% block title %}
  {{ object.name }} - {{ block.super }}
{% endblock %}

{% block content %}
<!--content part start-->
<section class="content_outer listing_main">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 content_inner">
        <div class="col-lg-10 listing_left">
          <ul>
            <li><a data-toggle="tab" href="#home">{% trans "News" %}</a></li>
            {% if is_in_group %}
            <li><a data-toggle="tab" href="#menu1">{% trans "members" %}</a></li>
            {% endif %}
          </ul>
        </div>
        <div class="col-lg-2 listing_left sm">
          <div class="dropdown mega-dropdown4">
            <a href="javascript:;"  id="menu4" class="direct dropdown-toggle invite_btn">{% trans "Invite Some Neighbors" %}  <i class="fa fa-caret-down"></i></a>
            <div class="dropdown-menu mega-dropdown-menu4 setting user_block direct_block">
              <div class="user_block_outer">
                <form action="{% url 'group:invite' object.pk %}" method="post">{% csrf_token %}
                  {% for neighbour in neighbours %}
                  <div class="user_block_top {% cycle 'gray' '' %}">
                    <div class="user_block_top_left"><img src="{{ neighbour.photo.url }}" alt=""></div>
                    <div class="user_block_top_right">
                        {{ neighbour.user.name }}
                      <input name="users" type="checkbox"  value="{{ neighbour.user.pk }}">
                    </div>
                  </div>
                  {% endfor %}
                  <input type="submit" value="{% trans "Invite" %}" class="btn">
                </form>
                <div class="user_bottom user_bottom_3" id="max-invites-reached">
                  {% trans "You reached maximum of 100 invites." %}
                </div>
              </div>
            </div>
          </div>
          <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
              <div class="about">
                <div class="about_left news">
                  <div class="about_me_outer news_left">
                    <div class="about_me">
                      <h3>info</h3>
                      <div class="msg_readable wdh">{{ object.description }}</div>
                      {% if is_in_group or object.status != object.STATUS_CLOSED %}
                        {% render_comment_list for object %}
                        {% render_comment_form for object %}
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="menu1" class="tab-pane fade">
              <div class="group_outer">
                <div class="units2">
                  <div class="units_left">
                    <h3>{% trans "Members" %}</h3>
                    <div class="units_left_top">
                      <ul>
                        {% for member in object.members.all %}
                        <li>
                          <a href="{{ member.get_absolute_url }}">
                            <b class="name_admin">{{ member.title }}</b>
                            <img alt="" src="{{ member.photo.url }}">
                          </a>
                          <span>{{ member.age|default_if_none:"" }}</span>
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                  <div class="units_left units_right">
                    <h3>{% trans "admins" %}</h3>
                    <div class="units_left_top">
                      <ul>
                        {% for admin in object.admins.all %}
                        <li>
                          <a href="{{ admin.get_absolute_url }}">
                            <b class="name_admin">{{ admin.name }}</b>
                            <img alt="" src="{{ admin.photo }}">
                          </a>
                          <span>{{ admin.age|default_if_none:"" }}</span>
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--content part end-->
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'fluent_comments/js/ajaxcomments.js' %}"></script>
    <script>
        (function() {
            var maxInvitesReached = document.querySelector('#max-invites-reached');

            var neighbours = document.querySelectorAll('.user_block_top_right');
            var neighbourInputs = document.querySelectorAll('.user_block_top_right input');
            var neighbourInputsChecked = document.querySelectorAll('.user_block_top_right input:checked');
            if (neighbourInputsChecked.length >= 100) {
                maxInvitesReached.style.display = 'block';
            } else {
                maxInvitesReached.style.display = 'none';
            }
            for (var i = 0; i < neighbourInputs.length; i++) {
                neighbourInputs[i].addEventListener('click', function(e) {
                    if (document.querySelectorAll('.user_block_top_right input:checked').length >= 100) {
                        maxInvitesReached.style.display = 'block';
                    } else {
                        maxInvitesReached.style.display = 'none';
                    }
                });
            }
        })();
    </script>
{% endblock %}